#include <iostream>
using namespace std;
int main()
{
	string x;
	while(cin>>x)
	{
		if(x=="brasil")
		{
			cout<<"Feliz Natal!\n";
		}
		else
		{
			if(x=="alemanha")
			{
				cout<<"Frohliche Weihnachten!\n";
			}
			else
			{
				if(x=="austria")
				{
					cout<<"Frohe Weihnacht!\n";
				}
				else
				{
					if(x=="coreia")
					{
						cout<<"Chuk Sung Tan!\n";
					}
					else
					{
						if(x=="espanha")
						{
							cout<<"Feliz Navidad!\n";
						}
						else
						{
							if(x=="grecia")
							{
								cout<<"Kala Christougena!\n";
							}
							else
							{
								if(x=="estados-unidos")
								{
									cout<<"Merry Christmas!\n";
								}
								else
								{
									if(x=="inglaterra")
									{
										cout<<"Merry Christmas!\n";
									}
									else
									{
										if(x=="australia")
										{
											cout<<"Merry Christmas!\n";
										}
										else
										{
											if(x=="portugal")
											{
												cout<<"Feliz Natal!\n";
											}
											else
											{
												if(x=="suecia")
												{
													cout<<"God Jul!\n";
												}
												else
												{
													if(x=="turquia")
													{
														cout<<"Mutlu Noeller\n";
													}
													else
													{
														if(x=="argentina")
														{
															cout<<"Feliz Navidad!\n";
														}
														else
														{
															if(x=="chile")
															{
																cout<<"Feliz Navidad!\n";
															}
															else
															{
																if(x=="mexico")
																{
																	cout<<"Feliz Navidad!\n";
																}
																else
																{
																	if(x=="antardida")
																	{
																		cout<<"Merry Christmas!\n";
																	}
																	else
																	{
																		if(x=="canada")
																		{
																			cout<<"Merry Christmas!\n";
																		}
																		else
																		{
																			if(x=="irlanda")
																			{
																				cout<<"Nollaig Shona Dhuit!\n";
																			}
																			else
																			{
																				if(x=="belgica")
																				{
																					cout<<"Zalig Kerstfeest!\n";
																				}
																				else
																				{
																					if(x=="italia")
																					{
																						cout<<"Buon Natale!\n";
																					}
																					else
																					{
																						if(x=="libia")
																						{
																							cout<<"Buon Natale!\n";
																						}
																						else
																						{
																							if(x=="siria")
																							{
																								cout<<"Milad Mubarak!\n";
																							}
																							else
																							{
																								if(x=="marrocos")
																								{
																									cout<<"Milad Mubarak!\n";
																								}
																								else
																								{
																									if(x=="japao")
																									{
																										cout<<"Merii Kurisumasu!\n";
																									}
																									else
																									{
																										cout<<"--- NOT FOUND ---\n";
																									}
																								}
																							}
																						}
																					}
																				}
																			}																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}