#include <bits/stdc++.h>
using namespace std;
int main()
{
	int l, c, i, j;
	cin >> l >> c >> i >> j;
	if (l % 2 == 0)
	{
		if (c % 2 == 0)
		{
			if (i % 2 == 0)
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
			else
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
		}
		else
		{
			if (i % 2 == 0)
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
			else
			{
				if (j % 2 == 0)
				{
					cout << "Esquerda" << endl;
				}
				else
				{
					cout << "Direita" << endl;
				}
			}
		}
	}
	else
	{
		if (c % 2 == 0)
		{
			if (i % 2 == 0)
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
			else
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
		}
		else
		{
			if (i % 2 == 0)
			{
				if (j % 2 == 0)
				{
					cout << "Direita" << endl;
				}
				else
				{
					cout << "Esquerda" << endl;
				}
			}
			else
			{
				if (j % 2 == 0)
				{
					cout << "Esquerda" << endl;
				}
				else
				{
					cout << "Direita" << endl;
				}
			}
		}
	}
}
